import pandas as pd
import os
import logging
import glob

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

def load_and_merge_data(base_data_dir: str) -> pd.DataFrame:
    """
    Loads raw CSVs and merges them into a single hourly DataFrame.
    """
    all_dfs = []

    # 1. Load Prices (Hourly) from ingested_prices directory
    ingested_prices_dir = os.path.join(base_data_dir, "ingested_prices")
    
    if not os.path.exists(ingested_prices_dir):
        logging.error(f"Ingested prices directory missing: {ingested_prices_dir}")
        return pd.DataFrame()

    price_files = glob.glob(os.path.join(ingested_prices_dir, "*.csv"))
    if not price_files:
        logging.warning(f"No electricity price files found in {ingested_prices_dir}")
        return pd.DataFrame()

    for price_file in sorted(price_files): # Process in chronological order
        try:
            df_price = pd.read_csv(price_file)
            # Consolidate column names if necessary
            if 'prices' in df_price.columns and 'price' not in df_price.columns:
                df_price = df_price.rename(columns={'prices': 'price'})
            elif 'prices' in df_price.columns and 'price' in df_price.columns:
                df_price['price'] = df_price['price'].fillna(df_price['prices'])
                df_price = df_price.drop(columns='prices')
            # Add condition to handle 'price_eur_per_mwh' column
            elif 'price_eur_per_mwh' in df_price.columns and 'price' not in df_price.columns:
                df_price = df_price.rename(columns={'price_eur_per_mwh': 'price'})
            # If 'price' already exists and 'price_eur_per_mwh' also exists, prefer 'price' and potentially drop the other.
            # For now, we assume 'price' is the primary target and 'price_eur_per_mwh' is an alternative if 'price' is missing.
            # If both exist, the current logic prefers 'price'. If 'price' is missing, it tries to rename 'prices'.
            # Adding the 'price_eur_per_mwh' case ensures it's also considered.
            
            all_dfs.append(df_price)
            logging.info(f"Loaded {os.path.basename(price_file)}")
        except Exception as e:
            logging.error(f"Error loading price file {price_file}: {e}")
            continue
            
    if not all_dfs:
        logging.error("No price data successfully loaded.")
        return pd.DataFrame()

    df = pd.concat(all_dfs, ignore_index=True)
    df['timestamp'] = pd.to_datetime(df['timestamp'], utc=True)
    df = df.sort_values(['timestamp', 'zone']).drop_duplicates(subset=['timestamp', 'zone']) # Handle potential duplicates from multiple files
    # Removed pivot and stack operations to keep zone as a separate column

    logging.info(f"All prices loaded. Total records: {len(df)}. Timestamp dtype: {df['timestamp'].dtype}")
    
    # 2. Load Weather from CSVs generated by the pipeline
    # We expect weather data to be saved in hourly CSVs, potentially within a 'ingested_weather' subdirectory.
    # The MET API fetches data for a specific location, so we assume it's not zone-specific here and will be merged by timestamp.
    weather_dir = os.path.join(base_data_dir, "ingested_weather")
    logging.info(f"Checking for weather data directory at: {weather_dir}") # Added debug logging
    if os.path.exists(weather_dir):
        weather_files = sorted(glob.glob(os.path.join(weather_dir, "*.csv")))
        if weather_files:
            all_weather_dfs = []
            for weather_file in weather_files:
                try:
                    df_weather = pd.read_csv(weather_file)
                    logging.info(f"Weather CSV columns before renaming: {df_weather.columns.tolist()}") # Log columns before rename
                    # Rename 'time' column to 'timestamp' for consistency with expected format
                    if 'time' in df_weather.columns and 'timestamp' not in df_weather.columns:
                        df_weather = df_weather.rename(columns={'time': 'timestamp'})
                    logging.info(f"Weather CSV columns after renaming attempt: {df_weather.columns.tolist()}") # Log columns after rename attempt
                    df_weather['timestamp'] = pd.to_datetime(df_weather['timestamp'], utc=True)
                    df_weather = df_weather.set_index('timestamp')
                    
                    # Define expected weather columns - now adjusted to what pipeline/no2_timeseries_pipeline.py generates
                    # We expect 'temperature' and 'precipitation'. 'wind_speed' might be missing.
                    available_weather_cols = ['temperature', 'precipitation']
                    
                    # Check if essential weather columns are present
                    if not all(col in df_weather.columns for col in ['temperature', 'precipitation']):
                        logging.warning(f"Weather file {os.path.basename(weather_file)} is missing essential weather columns ('temperature', 'precipitation'). Skipping.")
                        continue
                    
                    # Select only relevant weather columns that are present
                    # We are interested in temperature, precipitation, and potentially wind_speed if available.
                    # Filter available columns to only include those we are interested in.
                    cols_to_select = [col for col in ['temperature', 'wind_speed', 'precipitation'] if col in df_weather.columns]
                    df_weather = df_weather[cols_to_select]
                    
                    all_weather_dfs.append(df_weather)
                    logging.info(f"Loaded weather data from: {os.path.basename(weather_file)}. Shape: {df_weather.shape}")
                except Exception as e:
                    logging.error(f"Error loading weather file {weather_file}: {e}")
                    continue
            
            if all_weather_dfs:
                df_weather_combined = pd.concat(all_weather_dfs).sort_index()
                # For hourly data, we might need to resample or align if CSVs are not perfectly hourly or cover gaps.
                # Assuming here that the CSVs provide hourly data and we can merge directly.
                df = pd.merge(df, df_weather_combined, left_on='timestamp', right_index=True, how='left') # Merge on timestamp, weather is location-based
                logging.info(f"Weather data loaded and merged. Shape: {df_weather_combined.shape}")
            else:
                logging.warning("No valid weather data loaded from CSV files.")
        else:
            logging.warning(f"No weather CSV files found in {weather_dir}")
    else:
        logging.warning(f"Weather data directory not found: {weather_dir}")

    # 3. Load Hydrology (Commented out until data source is refactored to CSV)
    # hydrology_file = os.path.join(base_data_dir, "hydrology_no2.csv")
    # if os.path.exists(hydrology_file):
    #     df_hydrology = pd.read_csv(hydrology_file)
    #     df_hydrology['timestamp'] = pd.to_datetime(df_hydrology['timestamp'], utc=True)
    #     df_hydrology = df_hydrology.set_index('timestamp')
    #     df = pd.merge(df, df_hydrology, left_on='timestamp', right_index=True, how='left') # Merge on timestamp, assuming hydrology is not zone-specific
    #     logging.info(f"Hydrology data loaded. Shape: {df_hydrology.shape}")
    # else:
    #     logging.warning(f"Hydrology file not found: {hydrology_file}")

    # 3. Load Hydrology (Commented out until data source is refactored to CSV)
    # hydrology_file = os.path.join(base_data_dir, "hydrology_no2.csv")
    # if os.path.exists(hydrology_file):
    #     df_hydrology = pd.read_csv(hydrology_file)
    #     df_hydrology['timestamp'] = pd.to_datetime(df_hydrology['timestamp'], utc=True)
    #     df_hydrology = df_hydrology.set_index('timestamp')
    #     df = pd.merge(df, df_hydrology, left_on='timestamp', right_index=True, how='left') # Merge on timestamp, assuming hydrology is not zone-specific
    #     logging.info(f"Hydrology data loaded. Shape: {df_hydrology.shape}")
    # else:
    #     logging.warning(f"Hydrology file not found: {hydrology_file}")

    logging.info(f"DEBUG(data_loader): final df shape: {df.shape}")
    logging.info(f"DEBUG(data_loader): final df head:\n{df.head()}")
    logging.info(f"DEBUG(data_loader): final df tail:\n{df.tail()}")

    return df

if __name__ == "__main__":
    # Assuming data directory is relative to the project root
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.abspath(os.path.join(script_dir, os.pardir, os.pardir))
    data_dir_for_test = os.path.join(project_root, "data")
    
    logging.info(f"Attempting to load data from: {data_dir_for_test}")
    df = load_and_merge_data(data_dir_for_test)
    if not df.empty:
        logging.info("Data loaded successfully:")
        logging.info(df.head())
    else:
        logging.warning("No data loaded.")
